---

- hosts: ansi_master
  sudo: yes

  tasks:
  - name: Installing httpd on the master server
    yum: name=httpd state=present

  - name: Enabling the httpd service
    service: name=httpd enabled=yes state=started

  - name: Stopping the firewalld
    service: name=firewalld state=stopped
